version: '3.8'

services:
  app:
    build:
      context: .
    restart: unless-stopped
    command: npm run dev
    env_file:
      - ./.env
    ports:
      - $NODE_PORT:3000
    volumes:
      - ./:/code

  db:
    image: postgres:14.4
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_FORWARD_PORT:5432
    volumes:
      - db:/data/db

  adminer:
    image: adminer
    restart: always
    env_file: ./.env
    ports:
      - $ADMINER_PORT:8080

volumes:
  db:
    driver: local
