version: '3.8'

services:
  app:
    container_name: $APP_CONTAINER_NAME
    build:
      context: .
    restart: unless-stopped
    command: npm run dev
    env_file:
      - ./.env
    ports:
      - $NODE_PORT:3000
    volumes:
      - ./:/code

  db:
    container_name: $DB_CONTAINER_NAME
    image: postgres:14.4
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_FORWARD_PORT:5432
    volumes:
      - db:/data/db

  adminer:
    container_name: $ADMINER_CONTAINER_NAME
    image: adminer
    restart: always
    env_file: ./.env
    ports:
      - $ADMINER_PORT:8080

  mailhog:
    container_name: $MAILHOG_CONTAINER_NAME
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'

volumes:
  db:
    driver: local
